[package]
name = "learn-lmdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lmdb-rkv = "0.14.0"
lmdb-sys = "0.8.0"
scru128 = "2.2.0"
